"""Modify pet data

Revision ID: 94316de2dfad
Revises: 7f83631713d6
Create Date: 2025-01-14 16:36:45.835542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94316de2dfad'
down_revision = '7f83631713d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('adoption_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('sterilized', sa.Boolean(), nullable=False),
    sa.Column('microchip_number', sa.String(length=50), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('insurance_number', sa.String(length=50), nullable=True),
    sa.CheckConstraint("sex IN ('Male', 'Female', 'Unknown')", name='check_sex'),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('breed_id', sa.INTEGER(), nullable=True),
    sa.Column('species_id', sa.INTEGER(), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pets')
    # ### end Alembic commands ###
